### ISSUE TITLE
【集中帖】精翻部分文本问题反馈

### ISSUE THREAD

**Issue by RiccaSinicization** [RiccaSinicization/RICCA-Chinese-file-public-version#1]
可以在此贴反馈有关【精翻部分文本】的内容。

**Comment by OvaltineBoboIce** [comment]
您好，我想请问一下，我按照github上的教程汉化安装完成之后，打开游戏只有进入主菜单前的警告是中文的其余部分依然是英文，并且BepInEx控制台报了好多警告和一条错误，麻烦问一下你们之前有遇见过这种情况吗，有没有解决办法，期待回复，不胜感激。
![8 MADK)1{J AJ@FL$~{@U4](https://user-images.githubusercontent.com/105203647/167389834-3d3da6ff-15a3-4214-af0e-17d23b24ebe0.png)

**Comment by RiccaSinicization** [comment]
> 您好，我想请问一下，我按照github上的教程汉化安装完成之后，打开游戏只有进入主菜单前的警告是中文的其余部分依然是英文，并且BepInEx控制台报了好多警告和一条错误，麻烦问一下你们之前有遇见过这种情况吗，有没有解决办法，期待回复，不胜感激。 ![8 MADK)1{J AJ@FL$~{@U4](https://user-images.githubusercontent.com/105203647/167389834-3d3da6ff-15a3-4214-af0e-17d23b24ebe0.png)

@OvaltineBoboIce 根据我们已知信息，请检查以下内容：
1.路径是否存在中文字符
2.是否有其它插件处于激活状态，目前已知xunity插件可能与非bepinex插件管理器起冲突
3.如果仍有问题，请重新从dlsite下载安装包并解压，之后重新按照教程安装bepinex6与xunity5.0版本的插件
4.如果以上步解决不了问题，可以前往xunity项目或者bepinex项目寻找解决方法。

**Comment by OvaltineBoboIce** [comment]
明白了，非常感谢
