### ISSUE TITLE
【集中帖】说明文档问题反馈

### ISSUE THREAD

**Issue by RiccaSinicization** [RiccaSinicization/RICCA-Chinese-file-public-version#3]
可以在此贴反馈有关【说明文档】的内容。

**Comment by Bitter-Man** [comment]
你好，我在翻译《SuccubusReborn淫魔再诞》这个游戏时也用了XUnity.AutoTranslator，但是在！♡♪经常变成口，想创建TMP文件但是找不到教程和相关描述，试加载了你们的RiccaV13，发现可行，但是字体一粗一细的，希望能改一下，求TMP文件教程，我就做到用TMP做出SourceHanSansCN-Bold SDF.asset就不知道了

**Comment by RiccaSinicization** [comment]
> 你好，我在翻译《 SuccubusReborn 再诞》这个游戏时也用了 XUnity . AutoTranslator ，但是在！♡♪经常变成口，想创建 TMP 文件但是找不到教程和相关描述，试加载了你们的 RiccaV13 ，发现可行，但是字体一粗一细的，希望能改一下，求 TMP 文件教程，我就做到用 TMP 做出 SourceHanSansCN - Bold SDF . asset 就不知道了

@Bitter-Man 你好，[RiccaV13]和本项目其它字体是专门为特定游戏优化的字体。！♡♪经常变成口的问题是因为TMP字体的字符集中没有加入相关字符而导致变成口的问题（本项目的字体较xunity项目提供的字体增加了更多的符号）。字体一粗一细是因为你可能使用了fallback方式替换的字体，该方式将首先使用游戏内字体而在寻找不到游戏内字体后再用外部字体替换，所以内外部字体的差异将会体现。你可以使用overwrite方式强行使用外部字体替换（可能会出现BUG）。管理团队当前没有精力制作TMP字体的制作教程，你可以考虑加入本项目的技术反馈群询问，或者考虑前往B站搜索教程。

**Comment by Bitter-Man** [comment]
@RiccaSinicization 感谢回复，已经申请加群。
我是通过B站[失去我的我]的视频发现你们有TMP文件才找过来的，B站搜过没有教程(TMP文件 unity)，可能关键词不够准确。
看了[冰介]的视频，他用的是直接覆盖到游戏内，对于一月一更新的游戏不太友好啊。
现在发现[莴菽]有发现过TMP文件，但是他写不会做这个文件。
我目前就只会解包改浮点数去码，和在unity里创建字体资源的操作。
